/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VerifyEmailRouteImport } from "./routes/verify-email"
import { Route as TeamRouteImport } from "./routes/team"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as ProjectsRouteImport } from "./routes/projects"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as InviteRouteImport } from "./routes/invite"
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password"
import { Route as DashboardRouteImport } from "./routes/dashboard"
import { Route as CheckEmailRouteImport } from "./routes/check-email"
import { Route as BillingRouteImport } from "./routes/billing"
import { Route as AuditLogsRouteImport } from "./routes/audit-logs"
import { Route as AnalyticsRouteImport } from "./routes/analytics"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as DocsIndexRouteImport } from "./routes/docs/index"
import { Route as ProjectIdRouteImport } from "./routes/project.$id"
import { Route as DocsTemplatesRouteImport } from "./routes/docs/templates"
import { Route as DocsRequestLogsRouteImport } from "./routes/docs/request-logs"
import { Route as DocsRateLimitsRouteImport } from "./routes/docs/rate-limits"
import { Route as DocsQuickstartRouteImport } from "./routes/docs/quickstart"
import { Route as DocsOpenapiImportRouteImport } from "./routes/docs/openapi-import"
import { Route as DocsErrorsRouteImport } from "./routes/docs/errors"
import { Route as DocsEndpointsRouteImport } from "./routes/docs/endpoints"
import { Route as DocsChaosEngineeringRouteImport } from "./routes/docs/chaos-engineering"
import { Route as DocsAuthenticationRouteImport } from "./routes/docs/authentication"

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: "/team",
  path: "/team",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: "/invite",
  path: "/invite",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: "/check-email",
  path: "/check-email",
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: "/audit-logs",
  path: "/audit-logs",
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/docs/",
  path: "/docs/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: "/project/$id",
  path: "/project/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTemplatesRoute = DocsTemplatesRouteImport.update({
  id: "/docs/templates",
  path: "/docs/templates",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRequestLogsRoute = DocsRequestLogsRouteImport.update({
  id: "/docs/request-logs",
  path: "/docs/request-logs",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRateLimitsRoute = DocsRateLimitsRouteImport.update({
  id: "/docs/rate-limits",
  path: "/docs/rate-limits",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: "/docs/quickstart",
  path: "/docs/quickstart",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsOpenapiImportRoute = DocsOpenapiImportRouteImport.update({
  id: "/docs/openapi-import",
  path: "/docs/openapi-import",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsErrorsRoute = DocsErrorsRouteImport.update({
  id: "/docs/errors",
  path: "/docs/errors",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsEndpointsRoute = DocsEndpointsRouteImport.update({
  id: "/docs/endpoints",
  path: "/docs/endpoints",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChaosEngineeringRoute = DocsChaosEngineeringRouteImport.update({
  id: "/docs/chaos-engineering",
  path: "/docs/chaos-engineering",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAuthenticationRoute = DocsAuthenticationRouteImport.update({
  id: "/docs/authentication",
  path: "/docs/authentication",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/analytics": typeof AnalyticsRoute
  "/audit-logs": typeof AuditLogsRoute
  "/billing": typeof BillingRoute
  "/check-email": typeof CheckEmailRoute
  "/dashboard": typeof DashboardRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/invite": typeof InviteRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/projects": typeof ProjectsRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/team": typeof TeamRoute
  "/verify-email": typeof VerifyEmailRoute
  "/docs/authentication": typeof DocsAuthenticationRoute
  "/docs/chaos-engineering": typeof DocsChaosEngineeringRoute
  "/docs/endpoints": typeof DocsEndpointsRoute
  "/docs/errors": typeof DocsErrorsRoute
  "/docs/openapi-import": typeof DocsOpenapiImportRoute
  "/docs/quickstart": typeof DocsQuickstartRoute
  "/docs/rate-limits": typeof DocsRateLimitsRoute
  "/docs/request-logs": typeof DocsRequestLogsRoute
  "/docs/templates": typeof DocsTemplatesRoute
  "/project/$id": typeof ProjectIdRoute
  "/docs": typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/analytics": typeof AnalyticsRoute
  "/audit-logs": typeof AuditLogsRoute
  "/billing": typeof BillingRoute
  "/check-email": typeof CheckEmailRoute
  "/dashboard": typeof DashboardRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/invite": typeof InviteRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/projects": typeof ProjectsRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/team": typeof TeamRoute
  "/verify-email": typeof VerifyEmailRoute
  "/docs/authentication": typeof DocsAuthenticationRoute
  "/docs/chaos-engineering": typeof DocsChaosEngineeringRoute
  "/docs/endpoints": typeof DocsEndpointsRoute
  "/docs/errors": typeof DocsErrorsRoute
  "/docs/openapi-import": typeof DocsOpenapiImportRoute
  "/docs/quickstart": typeof DocsQuickstartRoute
  "/docs/rate-limits": typeof DocsRateLimitsRoute
  "/docs/request-logs": typeof DocsRequestLogsRoute
  "/docs/templates": typeof DocsTemplatesRoute
  "/project/$id": typeof ProjectIdRoute
  "/docs": typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/analytics": typeof AnalyticsRoute
  "/audit-logs": typeof AuditLogsRoute
  "/billing": typeof BillingRoute
  "/check-email": typeof CheckEmailRoute
  "/dashboard": typeof DashboardRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/invite": typeof InviteRoute
  "/login": typeof LoginRoute
  "/onboarding": typeof OnboardingRoute
  "/projects": typeof ProjectsRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/team": typeof TeamRoute
  "/verify-email": typeof VerifyEmailRoute
  "/docs/authentication": typeof DocsAuthenticationRoute
  "/docs/chaos-engineering": typeof DocsChaosEngineeringRoute
  "/docs/endpoints": typeof DocsEndpointsRoute
  "/docs/errors": typeof DocsErrorsRoute
  "/docs/openapi-import": typeof DocsOpenapiImportRoute
  "/docs/quickstart": typeof DocsQuickstartRoute
  "/docs/rate-limits": typeof DocsRateLimitsRoute
  "/docs/request-logs": typeof DocsRequestLogsRoute
  "/docs/templates": typeof DocsTemplatesRoute
  "/project/$id": typeof ProjectIdRoute
  "/docs/": typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/analytics"
    | "/audit-logs"
    | "/billing"
    | "/check-email"
    | "/dashboard"
    | "/forgot-password"
    | "/invite"
    | "/login"
    | "/onboarding"
    | "/projects"
    | "/register"
    | "/reset-password"
    | "/team"
    | "/verify-email"
    | "/docs/authentication"
    | "/docs/chaos-engineering"
    | "/docs/endpoints"
    | "/docs/errors"
    | "/docs/openapi-import"
    | "/docs/quickstart"
    | "/docs/rate-limits"
    | "/docs/request-logs"
    | "/docs/templates"
    | "/project/$id"
    | "/docs"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/analytics"
    | "/audit-logs"
    | "/billing"
    | "/check-email"
    | "/dashboard"
    | "/forgot-password"
    | "/invite"
    | "/login"
    | "/onboarding"
    | "/projects"
    | "/register"
    | "/reset-password"
    | "/team"
    | "/verify-email"
    | "/docs/authentication"
    | "/docs/chaos-engineering"
    | "/docs/endpoints"
    | "/docs/errors"
    | "/docs/openapi-import"
    | "/docs/quickstart"
    | "/docs/rate-limits"
    | "/docs/request-logs"
    | "/docs/templates"
    | "/project/$id"
    | "/docs"
  id:
    | "__root__"
    | "/"
    | "/analytics"
    | "/audit-logs"
    | "/billing"
    | "/check-email"
    | "/dashboard"
    | "/forgot-password"
    | "/invite"
    | "/login"
    | "/onboarding"
    | "/projects"
    | "/register"
    | "/reset-password"
    | "/team"
    | "/verify-email"
    | "/docs/authentication"
    | "/docs/chaos-engineering"
    | "/docs/endpoints"
    | "/docs/errors"
    | "/docs/openapi-import"
    | "/docs/quickstart"
    | "/docs/rate-limits"
    | "/docs/request-logs"
    | "/docs/templates"
    | "/project/$id"
    | "/docs/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BillingRoute: typeof BillingRoute
  CheckEmailRoute: typeof CheckEmailRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeamRoute: typeof TeamRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DocsAuthenticationRoute: typeof DocsAuthenticationRoute
  DocsChaosEngineeringRoute: typeof DocsChaosEngineeringRoute
  DocsEndpointsRoute: typeof DocsEndpointsRoute
  DocsErrorsRoute: typeof DocsErrorsRoute
  DocsOpenapiImportRoute: typeof DocsOpenapiImportRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsRateLimitsRoute: typeof DocsRateLimitsRoute
  DocsRequestLogsRoute: typeof DocsRequestLogsRoute
  DocsTemplatesRoute: typeof DocsTemplatesRoute
  ProjectIdRoute: typeof ProjectIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/team": {
      id: "/team"
      path: "/team"
      fullPath: "/team"
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects": {
      id: "/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invite": {
      id: "/invite"
      path: "/invite"
      fullPath: "/invite"
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/check-email": {
      id: "/check-email"
      path: "/check-email"
      fullPath: "/check-email"
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/billing": {
      id: "/billing"
      path: "/billing"
      fullPath: "/billing"
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/audit-logs": {
      id: "/audit-logs"
      path: "/audit-logs"
      fullPath: "/audit-logs"
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/analytics": {
      id: "/analytics"
      path: "/analytics"
      fullPath: "/analytics"
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/": {
      id: "/docs/"
      path: "/docs"
      fullPath: "/docs"
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/project/$id": {
      id: "/project/$id"
      path: "/project/$id"
      fullPath: "/project/$id"
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/templates": {
      id: "/docs/templates"
      path: "/docs/templates"
      fullPath: "/docs/templates"
      preLoaderRoute: typeof DocsTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/request-logs": {
      id: "/docs/request-logs"
      path: "/docs/request-logs"
      fullPath: "/docs/request-logs"
      preLoaderRoute: typeof DocsRequestLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/rate-limits": {
      id: "/docs/rate-limits"
      path: "/docs/rate-limits"
      fullPath: "/docs/rate-limits"
      preLoaderRoute: typeof DocsRateLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/quickstart": {
      id: "/docs/quickstart"
      path: "/docs/quickstart"
      fullPath: "/docs/quickstart"
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/openapi-import": {
      id: "/docs/openapi-import"
      path: "/docs/openapi-import"
      fullPath: "/docs/openapi-import"
      preLoaderRoute: typeof DocsOpenapiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/errors": {
      id: "/docs/errors"
      path: "/docs/errors"
      fullPath: "/docs/errors"
      preLoaderRoute: typeof DocsErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/endpoints": {
      id: "/docs/endpoints"
      path: "/docs/endpoints"
      fullPath: "/docs/endpoints"
      preLoaderRoute: typeof DocsEndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/chaos-engineering": {
      id: "/docs/chaos-engineering"
      path: "/docs/chaos-engineering"
      fullPath: "/docs/chaos-engineering"
      preLoaderRoute: typeof DocsChaosEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/authentication": {
      id: "/docs/authentication"
      path: "/docs/authentication"
      fullPath: "/docs/authentication"
      preLoaderRoute: typeof DocsAuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditLogsRoute: AuditLogsRoute,
  BillingRoute: BillingRoute,
  CheckEmailRoute: CheckEmailRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeamRoute: TeamRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DocsAuthenticationRoute: DocsAuthenticationRoute,
  DocsChaosEngineeringRoute: DocsChaosEngineeringRoute,
  DocsEndpointsRoute: DocsEndpointsRoute,
  DocsErrorsRoute: DocsErrorsRoute,
  DocsOpenapiImportRoute: DocsOpenapiImportRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsRateLimitsRoute: DocsRateLimitsRoute,
  DocsRequestLogsRoute: DocsRequestLogsRoute,
  DocsTemplatesRoute: DocsTemplatesRoute,
  ProjectIdRoute: ProjectIdRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
